### ISSUE TITLE
kdenlive does not start

### ISSUE THREAD

**Issue by 1099511627776** [forwardcomputers/dockerfiles#1]
Docker version 18.06.1-ce, build e68fc7a
Command line: sudo docker run -it -v /tmp/.X11-unix:/tmp/.X11-unix -v $HOME/Vídeos:/videos --device=/dev/dri --device=/dev/snd -e DISPLAY=unix$DISPLAY --name knl
 forwardcomputers/kdenlive

Error: kdenlive: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory

**Comment by forwardcomputers** [comment]
Just ran the image on a Debian Live CD. 
Did not get your error message !

There are some warnings that I need to sort out thou.

![Screen Shot 2020-06-25 at 1 57 16 PM](https://user-images.githubusercontent.com/39178654/85773415-d0826e00-b6eb-11ea-86aa-d637c15a525b.png)
