### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by ovizii** [forwardcomputers/dockerfiles#2]
Hi there,

I was looking to get openshot running and accessing i.e. via VNC or similar. I found your image here: https://hub.docker.com/r/forwardcomputers/openshot and was wondering if you have any docs for using it. 

Before finding your image I was thinking of building my own to access it via VNC. Three is a nice framework do doing so here: https://github.com/jlesage/docker-baseimage-gui but I was wondering whether I might skip that work and use yours.

**Comment by forwardcomputers** [comment]
Hi,

This container does not have any X11/VNC components in it, it relies on the host to have X server to be able to function.

The way I would run this image

```
# xhost + LOCAL: 127.0.0.1
 
# docker container run --detach --rm \
--network=host --name openshot --hostname=docker_openshot --shm-size=1gb \
--env HOME="${HOME}" \
--env DISPLAY=unix"${DISPLAY}" \
--env PULSE_SERVER=unix:/run/user/"${UID}"/pulse/native \
--device /dev/bus/usb \
--device /dev/dri \
--device /dev/snd \
--volume /etc/machine-id:/etc/machine-id:ro \
--volume /run/user/"${UID}"/pulse:/run/user/1001/pulse)
--volume /tmp/.X11-unix:/tmp/.X11-unix:rw \
--volume "${HOME}":/home/duser \
--user $(id -u ${USER}):$(id -g ${USER}) \
--workdir "${HOME}" \
forwardcomputers/openshot --security-opt apparmor=unconfined
```
